version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.intellaclick.com`)"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/intellaclick
    depends_on:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=intellaclick
    restart: unless-stopped

volumes:
  mongo_data: